
/* Drop Tables */

DROP TABLE LIKES CASCADE CONSTRAINTS;
DROP TABLE READERCOMMENT CASCADE CONSTRAINTS;
DROP TABLE BBS CASCADE CONSTRAINTS;
DROP TABLE IMAGE CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SEQ_LIKES_LNO;




/* Create Sequences */

CREATE SEQUENCE SEQ_LIKES_LNO INCREMENT BY 1 START WITH 1;



/* Create Tables */

CREATE TABLE BBS
(
	NO number NOT NULL,
	ID varchar2(20) NOT NULL,
	TITLE nvarchar2(500) NOT NULL,
	CONTENT nvarchar2(2000) NOT NULL,
	VISTCOUNT number DEFAULT 0 NOT NULL,
	POSTDATE date DEFAULT SYSDATE NOT NULL,
	ATTACHFILE varchar2(2000),
	DOWNCOUNT number DEFAULT 0,
	PRIMARY KEY (NO)
);


CREATE TABLE IMAGE
(
	ID varchar2(20) NOT NULL,
	IMAGE nvarchar2(1000)
);


CREATE TABLE LIKES
(
	LNO number NOT NULL,
	NO number NOT NULL,
	ID varchar2(20) NOT NULL,
	LIKEDATE date DEFAULT SYSDATE,
	PRIMARY KEY (LNO)
);


CREATE TABLE MEMBER
(
	ID varchar2(20) NOT NULL,
	PASSWORD varchar2(30) NOT NULL,
	NAME varchar2(20) NOT NULL,
	PERSONID nvarchar2(20) NOT NULL UNIQUE,
	GENDER nvarchar2(20) DEFAULT 'MAN' NOT NULL,
	ADDR varchar2(500) NOT NULL,
	PHONENUMBER nvarchar2(20) NOT NULL UNIQUE,
	INTERS varchar2(500),
	EDUCATION nvarchar2(50),
	SELFINTRODUCE nvarchar2(2000),
	REGIDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE READERCOMMENT
(
	CNO number NOT NULL,
	ID varchar2(20) NOT NULL,
	NO number NOT NULL,
	TEXT nvarchar2(1000),
	ROOT number,
	STEP number,
	RANK number,
	CCOMMENT number,
	PCOMMENT number DEFAULT 0,
	WRITEDATE date DEFAULT SYSDATE NOT NULL,
	PRIMARY KEY (CNO)
);



/* Create Foreign Keys */

ALTER TABLE LIKES
	ADD FOREIGN KEY (NO)
	REFERENCES BBS (NO)
;


ALTER TABLE READERCOMMENT
	ADD FOREIGN KEY (NO)
	REFERENCES BBS (NO)
;


ALTER TABLE BBS
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE IMAGE
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE LIKES
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;


ALTER TABLE READERCOMMENT
	ADD FOREIGN KEY (ID)
	REFERENCES MEMBER (ID)
;



